Servicio Meteorologico realizado
vikour/PVTranslatorREST pull request #6
Opened 2018-12-07 18:28 UTC by torino09

He creado un nuevo botón llamado "Ver el tiempo" en index.xhtml, al pulsarlo llevará a la página "verTiempo.xhtml", en esta página se verá una tabla de 10 filas de datos.

Cada fila es una medición del tiempo según la fecha.

Las columnas mostradas son:
Descripción del tiempo | Temperatura | Velocidad del viento | Dirección del viento | Porcentaje de nubes | Humedad | Fecha

Se ha colocado 3 botones, uno para ver las siguientes mediciones, otro para ver las mediciones anteriores y el ultimo para volver a index.xhtml. Los botones se llaman "Fechas anteriores", "Fechas posteriores" y "Atras", pero "Fechas anteriores" y "Fechas posteriores" sólo serán visibles cuando sea posible ver las anteriores o siguientes mediciones.

2018-12-07 20:46 UTC, tretox requested changes
Me parece todo correcto, lo único que yo cambiaría, a parte de lo de las flechas (-> y <-) en los botones de las fechas, es que el botón de ver el tiempo saliera en linea con el resto de botones (a la derecha de importar)

2018-12-07 21:05 UTC, torino09 commented
Deje el botón de ver el tiempo debajo para separarlo de los botones relacionadas con los módulos y las campañas, y así a simple vista se nota que sirve para otra cosa, aunque también podría ponerse de otro color para distinguirlo bien

2018-12-08 19:16 UTC, vikour commented
> Deje el botón de ver el tiempo debajo para separarlo de los botones relacionadas con los módulos y las campañas, y así a simple vista se nota que sirve para otra cosa, aunque también podría ponerse de otro color para distinguirlo bien

2018-12-08 19:38 UTC, vikour requested changes
He puesto algunos comentarios en el código sobre qué se podría hacer.
Con respecto a lo de poner el botón seguido del de nuevo e importar, no me importa que esté debajo. Pero por seguir concordancia con el calendario... La solución va a ser o bajar el calendario o subir el tiempo.

¿Cómo se ponen los iconos? Lo que he seguido para hacer esto está recogido en la siguiente página web: [https://www.w3schools.com/icons/google_icons_intro.asp](url)

Lo que pongas como texto en el contenedor que tenga la clase _materials_icons_ se sustituirá por un icono. Tienes ejemplos en la página que te he pasado y en la propia aplicación, mira los botones del index.

2018-12-08 19:38 UTC, vikour commented on A6ClienteRest/web/index.xhtml
> +                <h:form>
Creo que esto no tendría que estar aqui, si no junto con los demás botones, para que aparezcan uno al lado del otro (si es esto lo que se quiere). Por lo que se podría eliminar el h:form, ya que hay uno que engloba a toda la tabla y a los botones.

2018-12-08 19:38 UTC, vikour commented on A6ClienteRest/web/index.xhtml
> +                    <h:commandLink   class="btn btn-primary"
Esto debería ser responsive con su icono, el formato seguido es :
```suggestion
                 <h:commandLink type="link" class="btn btn-primary rounded" 
                                       action="ACCION_BEANS">
                            <span class="material-icons align-middle">
                                NOMBRE DEL ICONO
                            </span>
                            <span class="d-none d-md-inline-block align-middle">
                                NOMBRE DEL BOTON
                            </span>
                        </h:commandLink>
```
Sustituye las palabras en mayúsculas.

2018-12-08 19:38 UTC, vikour commented on A6ClienteRest/web/verTiempo.xhtml
> +                    <h:commandLink id="atras" type="link" class="btn btn-primary rounded"
En este caso, no podría el icono,  está bien. Porque en el formulario no tiene icono de hacia atrás. Así que me parece bien que lo dejes como está.

2018-12-09 12:17 UTC, tretox approved these changes

2018-12-09 12:17 UTC, vikour approved these changes

2018-12-09 12:55 UTC, merged